#!/bin/sh -e

systemctl enable snapd

while ! kill -0 $(pidof snapd) 2>/dev/null; do
  echo "Waiting for snapd to start."
  sleep 1
done

/usr/bin/snap $@

snap install intellij-idea-ultimate --classic
